# Generated by Django 5.0.6 on 2024-08-02 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='title',
            field=models.CharField(default='default-title', max_length=100),
        ),
        migrations.AddField(
            model_name='codefile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
